### ISSUE TITLE
Can't Reach /admin

### ISSUE THREAD

**Issue by MaxLFarrell** [jaredly/hexo-admin#60]
I cannot reach /admin 
Hexo runs with no errors
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/blog/. Press Ctrl+C to stop.
```
My packages.config file is as follows
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-admin": "^2.0.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

Possibly relevant are the facts that I'm reverse-proxying http://localhost:4000/blog/ to a sub-domain of /blog so I'm trying to reach /blog/admin and that it shows no sign of hexo-admin starting

**Comment by v123582** [comment]
i have same problem because the root url is not '/'.
u can check this pr: #57

**Comment by jaredly** [comment]
@MaxLFarrell I just merged #57 -- can you run hexo-admin from `master` and see if it works?

**Comment by MaxLFarrell** [comment]
@jaredly I apologize I'm pretty new to node, do I do this in my packages.json as shown below? 
```
{                                       
  "name": "hexo-site",                  
  "version": "0.0.0",                   
  "private": true,                      
  "hexo": {                             
    "version": "3.2.0"                  
  },                                    
  "dependencies": {                     
    "hexo": "^3.2.0",                   
    "hexo-admin": "../hexo-admin",      
    "hexo-generator-archive": "^0.1.4", 
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",   
    "hexo-generator-tag": "^0.2.0",     
    "hexo-renderer-ejs": "^0.2.0",      
    "hexo-renderer-marked": "^0.2.10",  
    "hexo-renderer-stylus": "^0.3.1",   
    "hexo-server": "^0.2.0"             
  }                                     
}                                       
```

**Comment by v123582** [comment]
@MaxLFarrell I think you must clone code from github, and put it in npm_modules.

**Comment by MaxLFarrell** [comment]
`npm install --save <https://foo.git>` works. It adds it to my dependencies and to my packages.config. However I still have the original problem. Another relevant point that I will add to the original is that it shows no sign of hexo-admin starting. I don't know if it's supposed to or not.

**Comment by v123582** [comment]
@MaxLFarrell can u check the npm_modules//hexo-admin/www have bundle.js? 
If bundle.js don't exist, you can pre-install(using grunt) on npm_modules//hexo-admin.

**Comment by MaxLFarrell** [comment]
@v123582 I've got bundle.js. What's the best way to check if hexo-admin is running at all? Does it throw up a flag on `hexo server -d` ?

**Comment by v123582** [comment]
@MaxLFarrell , I don't know it. 

But if bundle.js exist in it , it should run. cannot you reach /admin  now?:(

**Comment by MaxLFarrell** [comment]
@v123582
Sorry no.
I run:
`hexo server -d`
and get:
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/blog/. Press Ctrl+C to stop. 
```
If you go to http://arcane.info/blog you can see the blog I'm trying to run but try going to http://arcane.info/blog/admin/ .

**Comment by MaxLFarrell** [comment]
@v123582 @jaredly Is it possible that the admin panel is not running at http://localhost:4000/blog/admin but instead at http://localhost:4000:/admin ?

**Comment by v123582** [comment]
@MaxLFarrell can see your _config.yml in hexo project?

**Comment by MaxLFarrell** [comment]
@v123582  Yeah
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com/blog/
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```
In the extensions sections should I be putting hexo-admin under plugins somewhere?

**Comment by MaxLFarrell** [comment]
@v123582 @jaredly 

Alright so I've got it. Basically what's happening is the admin panel is running at http://127.0.0.1:4000/blog/admin/, however node doesn't like it running there because hexo-admin (if i understand correctly) basically runs as a separate application so I basically needed to reverse proxy that url specifically so I ended up added the following to my apache2 config:
```
ProxyPass /admin http://127.0.0.1:4000/blog/admin/
ProxyPassReverse /admin http://127.0.0.1:4000/blog/admin/
```

Thanks to both of you for all the help!

**Comment by v123582** [comment]
I set the new project again and it can work:

1. mkdir blog & cd blog, and set config root: /blog
2. hexo init & npm i
3. npm install --save https://github.com/jaredly/hexo-admin.git
4. cd node_modules/hexo-admin
5. gulp
6. cd ../../
7. hexo server -d

**Comment by eddy1937** [comment]
@jaredly @v123582 @agieocean 

I'm encountering the same issue. I can only edit my blog posts by going to http://localhost:4000/blog/admin.
Furthermore, when I paste an image using the Ctrl + V shortcut, the image URL is as follows:

```
![upload successful](/blog/images/pasted-9.png)
```

This results in the image path being 

```
http://localhost:4000/blog/blog/images/pasted-9.png
```

http://.../blog/blog/...  (incorrect path)
